#!/usr/bin/env python3
"""Export graphify graph.json to Obsidian vault markdown files."""

import json
import os
import sys
from pathlib import Path
from collections import defaultdict

def export_to_obsidian(graph_path, vault_path):
    """Convert graph.json to Obsidian markdown notes."""
    with open(graph_path) as f:
        graph = json.load(f)
    
    nodes = {n['id']: n for n in graph.get('nodes', [])}
    edges = graph.get('edges', [])
    
    # Build adjacency list
    connections = defaultdict(list)
    for edge in edges:
        src = edge.get('source', edge.get('from', ''))
        tgt = edge.get('target', edge.get('to', ''))
        if src in nodes and tgt in nodes:
            connections[src].append(tgt)
            connections[tgt].append(src)
    
    # Create output directory
    code_dir = Path(vault_path) / 'notes' / 'code'
    code_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate notes for each node
    created = 0
    for node_id, node in nodes.items():
        label = node.get('label', node_id)
        source_file = node.get('sourceFile', '')
        file_type = node.get('fileType', 'unknown')
        source_location = node.get('sourceLocation', '')
        
        # Create safe filename
        safe_name = label.replace('/', '-').replace('.', '-').replace(' ', '-')
        note_path = code_dir / f'{safe_name}.md'
        
        # Get connected nodes
        related = connections.get(node_id, [])
        related_notes = []
        for rel_id in related:
            rel_node = nodes.get(rel_id, {})
            rel_label = rel_node.get('label', rel_id)
            rel_safe = rel_label.replace('/', '-').replace('.', '-').replace(' ', '-')
            related_notes.append(f'[[{rel_safe}]]')
        
        # Generate markdown
        content = f"""---
title: {label}
tags: [code, {file_type}]
source: {source_file}
created: 2026-06-17
---

# {label}

**Type**: {file_type}
**Source**: `{source_file}`
**Location**: `{source_location}`

## Connected Symbols
{chr(10).join(f'- {r}' for r in related_notes) if related_notes else '- No connections'}

## Source File
```{file_type}
// See: {source_file}
```
"""
        note_path.write_text(content)
        created += 1
    
    # Create index note
    index_content = f"""---
title: Career Portal Code Index
tags: [index, code, graphify]
created: 2026-06-17
---

# Career Portal Code Index

Generated by Graphify from `{len(nodes)}` symbols and `{len(edges)}` relationships.

## All Symbols
"""
    for node_id, node in sorted(nodes.items(), key=lambda x: x[1].get('label', '')):
        label = node.get('label', node_id)
        safe_name = label.replace('/', '-').replace('.', '-').replace(' ', '-')
        file_type = node.get('fileType', 'unknown')
        index_content += f'- [[{safe_name}|{label}]] ({file_type})\n'
    
    index_path = code_dir / 'INDEX.md'
    index_path.write_text(index_content)
    created += 1
    
    print(f'Exported {created} notes to {code_dir}')
    return created

if __name__ == '__main__':
    graph_path = sys.argv[1] if len(sys.argv) > 1 else 'graphify-out/graph.json'
    vault_path = sys.argv[2] if len(sys.argv) > 2 else os.path.expanduser('~/obsidian-vault')
    export_to_obsidian(graph_path, vault_path)
